// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace MntPlus.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240404222525_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EquipmentId");

                    b.Property<string>("EquipmentCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EquipmentImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EquipmentMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentNameImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EquipmentParent")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab837407-ff51-4c0c-a9e9-bbce2786a169"),
                            EquipmentCategory = "Category A",
                            EquipmentImage = new byte[0],
                            EquipmentMake = "Make Y",
                            EquipmentModel = "Model X",
                            EquipmentName = "Equipment 1",
                            EquipmentNameImage = "equipment1.jpg"
                        },
                        new
                        {
                            Id = new Guid("208e643b-3694-47ac-ba1d-f57fb3b34930"),
                            EquipmentCategory = "Category B",
                            EquipmentImage = new byte[0],
                            EquipmentMake = "Make X",
                            EquipmentModel = "Model Z",
                            EquipmentName = "Equipment 2",
                            EquipmentNameImage = "equipment2.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
